spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    usename: postgres
    password: fabrica2023*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-patagorm: org.hibernate.dialect.PostgreSQLDialect






